import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { Card,CardContent,CardHeader,CardTitle,CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select'; import { Badge } from '@/components/ui/badge';
import { MessageSquare,Plus,Clock } from 'lucide-react'; import { toast } from 'sonner'; import { mensagemDeErro } from '@/lib/erros';

export default function CentralSuporte(){
 const {profile,isPlatformAdmin,user}=useSupabaseAuth(); const qc=useQueryClient(); const [titulo,setTitulo]=useState(''); const [descricao,setDescricao]=useState(''); const [prioridade,setPrioridade]=useState('normal'); const [selecionado,setSelecionado]=useState<any>(null); const [mensagem,setMensagem]=useState('');
 const tickets=useQuery({queryKey:['support-tickets'],queryFn:async()=>{const {data,error}=await (supabase as any).from('support_tickets').select('*').order('created_at',{ascending:false});if(error)throw error;return data||[]}});
 const mensagens=useQuery({queryKey:['support-messages',selecionado?.id],enabled:!!selecionado,queryFn:async()=>{const {data,error}=await (supabase as any).from('support_ticket_messages').select('*').eq('ticket_id',selecionado.id).order('created_at');if(error)throw error;return data||[]}});
 const criar=async()=>{try{const {error}=await (supabase as any).from('support_tickets').insert({titulo,descricao,prioridade,clinica_id:profile?.clinica_id,solicitante_id:user?.id,sla_limite:new Date().toISOString()});if(error)throw error;setTitulo('');setDescricao('');qc.invalidateQueries({queryKey:['support-tickets']});toast.success('Chamado aberto.')}catch(e){toast.error('Não foi possível abrir o chamado.',{description:mensagemDeErro(e)})}};
 const responder=async()=>{if(!mensagem.trim()||!selecionado)return;const {error}=await (supabase as any).from('support_ticket_messages').insert({ticket_id:selecionado.id,autor_id:user?.id,mensagem});if(error){toast.error(mensagemDeErro(error));return}setMensagem('');qc.invalidateQueries({queryKey:['support-messages',selecionado.id]})};
 const status=async(id:string,value:string)=>{const {error}=await (supabase as any).from('support_tickets').update({status:value,resolvido_em:value==='resolvido'?new Date().toISOString():null}).eq('id',id);if(error)toast.error(mensagemDeErro(error));else qc.invalidateQueries({queryKey:['support-tickets']})};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold flex items-center gap-2"><MessageSquare className="h-6 w-6"/>Central de Suporte</h1><p className="text-muted-foreground">Chamados, prioridade, SLA e histórico em um só lugar.</p></div>
 {!isPlatformAdmin&&<Card><CardHeader><CardTitle className="text-base">Abrir chamado</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={titulo} onChange={e=>setTitulo(e.target.value)} placeholder="Resumo do problema"/><Textarea value={descricao} onChange={e=>setDescricao(e.target.value)} placeholder="Descreva o que aconteceu e como reproduzir"/><Select value={prioridade} onValueChange={setPrioridade}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['baixa','normal','alta','critica'].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select><Button onClick={criar} disabled={titulo.trim().length<5||descricao.trim().length<10}><Plus className="mr-2 h-4 w-4"/>Abrir chamado</Button></CardContent></Card>}
 <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Fila de chamados</CardTitle><CardDescription>{tickets.data?.length||0} chamado(s)</CardDescription></CardHeader><CardContent className="space-y-2">{tickets.data?.map((t:any)=><div key={t.id} className="w-full rounded-lg border p-3"><button type="button" onClick={()=>setSelecionado(t)} className="w-full text-left hover:opacity-80"><div className="flex justify-between gap-2"><strong>{t.titulo}</strong><Badge variant={t.prioridade==='critica'?'destructive':'outline'}>{t.prioridade}</Badge></div><p className="mt-1 text-xs text-muted-foreground"><Clock className="mr-1 inline h-3 w-3"/>SLA {new Date(t.sla_limite).toLocaleString('pt-BR')}</p></button>{isPlatformAdmin&&<Select value={t.status} onValueChange={v=>status(t.id,v)}><SelectTrigger className="mt-2 h-8" aria-label={`Status do chamado ${t.titulo}`}><SelectValue/></SelectTrigger><SelectContent>{['aberto','em_atendimento','aguardando_cliente','resolvido','fechado'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select>}</div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle className="text-base">{selecionado?.titulo||'Selecione um chamado'}</CardTitle></CardHeader><CardContent className="space-y-3">{selecionado&&<><p className="text-sm">{selecionado.descricao}</p><div className="max-h-72 space-y-2 overflow-auto">{mensagens.data?.map((m:any)=><div key={m.id} className="rounded-lg bg-muted p-2 text-sm">{m.mensagem}<p className="text-[10px] text-muted-foreground">{new Date(m.created_at).toLocaleString('pt-BR')}</p></div>)}</div><Textarea value={mensagem} onChange={e=>setMensagem(e.target.value)} placeholder="Escreva uma resposta"/><Button onClick={responder}>Responder</Button></>}</CardContent></Card></div></div>
}
