import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { CheckCircle2, Clock3, Lightbulb, MessageSquarePlus, RefreshCw, ShieldCheck } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { mensagemDeErro } from '@/lib/erros';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { ErrorState } from '@/components/ErrorState';

type Feedback={id:string;protocolo:string;categoria:string;mensagem:string;contexto:Record<string,string>;status:string;resposta_publica:string|null;created_at:string};
const categories:Record<string,string>={duvida:'Dúvida',problema:'Problema',sugestao:'Sugestão',elogio:'Elogio',acessibilidade:'Acessibilidade'};
const statuses:Record<string,string>={recebido:'Recebido',em_analise:'Em análise',planejado:'Planejado',resolvido:'Resolvido',encerrado:'Encerrado'};

function AdminReply({item,onSaved}:{item:Feedback;onSaved:()=>void}){
 const[response,setResponse]=useState(item.resposta_publica||''),[saving,setSaving]=useState(false);
 const save=async()=>{setSaving(true);const{error}=await(supabase as any).rpc('manage_product_feedback',{p_id:item.id,p_status:item.status,p_resposta:response.trim()});setSaving(false);if(error)toast.error('Falha ao responder',{description:mensagemDeErro(error)});else{toast.success('Resposta publicada');onSaved()}};
 return <div className="grid gap-2"><Label htmlFor={`reply-${item.id}`}>Resposta pública</Label><Textarea id={`reply-${item.id}`} value={response} onChange={e=>setResponse(e.target.value)} maxLength={2000} rows={3}/><Button variant="outline" className="min-h-11 justify-self-start" disabled={response.trim().length<2||saving} onClick={save}>{saving?'Salvando…':'Publicar resposta'}</Button></div>;
}

export default function FeedbackProduto(){
 const{isPlatformAdmin}=useSupabaseAuth(),qc=useQueryClient();
 const[categoria,setCategoria]=useState('sugestao'),[mensagem,setMensagem]=useState(''),[tela,setTela]=useState(''),[acao,setAcao]=useState(''),[erro,setErro]=useState('');
 const query=useQuery({queryKey:['product-feedback',isPlatformAdmin],queryFn:async()=>{const{data,error}=await(supabase as any).from('product_feedback').select('id,protocolo,categoria,mensagem,contexto,status,resposta_publica,created_at').order('created_at',{ascending:false}).limit(100);if(error)throw error;return(data||[])as Feedback[]}});
 const submit=useMutation({mutationFn:async()=>{const contexto=Object.fromEntries(Object.entries({tela,acao,erro}).filter(([,v])=>v.trim()));const{data,error}=await(supabase as any).rpc('submit_product_feedback',{p_categoria:categoria,p_mensagem:mensagem,p_contexto:contexto});if(error)throw error;return data?.[0]},onSuccess:r=>{setMensagem('');setTela('');setAcao('');setErro('');qc.invalidateQueries({queryKey:['product-feedback']});toast.success('Feedback enviado',{description:`Protocolo ${r?.protocolo}.`})},onError:e=>toast.error('Não foi possível enviar',{description:mensagemDeErro(e)})});
 const update=useMutation({mutationFn:async({id,status}:{id:string;status:string})=>{const current=items.find(item=>item.id===id);const{error}=await(supabase as any).rpc('manage_product_feedback',{p_id:id,p_status:status,p_resposta:current?.resposta_publica||null});if(error)throw error},onSuccess:()=>qc.invalidateQueries({queryKey:['product-feedback']}),onError:e=>toast.error('Falha ao atualizar',{description:mensagemDeErro(e)})});
 const items=query.data||[],valid=mensagem.trim().length>=10&&mensagem.length<=2000;
 return <div className="mx-auto max-w-5xl space-y-6 pb-8"><header><h1 className="flex items-center gap-2 text-2xl font-bold"><MessageSquarePlus className="h-6 w-6 text-primary"/>Feedback do produto</h1><p className="mt-1 text-sm text-muted-foreground">{isPlatformAdmin?'Acompanhe sugestões e problemas enviados pelos usuários.':'Conte o que podemos melhorar e acompanhe a resposta pelo protocolo.'}</p></header>
 {!isPlatformAdmin&&<Card><CardHeader><CardTitle className="text-lg">Enviar feedback</CardTitle><CardDescription>Não inclua nomes de pacientes, CPF, prontuários, senhas ou tokens. Nenhum contexto técnico é coletado automaticamente.</CardDescription></CardHeader><CardContent className="space-y-5">
  <div className="grid gap-2"><Label htmlFor="feedback-category">Categoria</Label><Select value={categoria} onValueChange={setCategoria}><SelectTrigger id="feedback-category" className="min-h-11"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(categories).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>
  <div className="grid gap-2"><Label htmlFor="feedback-message">Mensagem</Label><Textarea id="feedback-message" value={mensagem} onChange={e=>setMensagem(e.target.value)} maxLength={2000} rows={6} aria-describedby="feedback-counter" placeholder="Descreva sua ideia ou o que não funcionou (sem dados de pacientes)."/><p id="feedback-counter" className="text-xs text-muted-foreground" aria-live="polite">{mensagem.length}/2000 caracteres · mínimo de 10</p></div>
  <details className="rounded-lg border p-4"><summary className="min-h-11 cursor-pointer font-medium focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Adicionar contexto técnico (opcional)</summary><div className="mt-4 grid gap-4"><p className="text-xs text-muted-foreground">Preencha apenas informações operacionais. Nada é preenchido automaticamente.</p><div className="grid gap-2"><Label htmlFor="feedback-screen">Tela ou módulo</Label><Input id="feedback-screen" value={tela} onChange={e=>setTela(e.target.value)} maxLength={100}/></div><div className="grid gap-2"><Label htmlFor="feedback-action">O que você tentou fazer?</Label><Input id="feedback-action" value={acao} onChange={e=>setAcao(e.target.value)} maxLength={300}/></div><div className="grid gap-2"><Label htmlFor="feedback-error">Mensagem de erro (sem dados pessoais)</Label><Textarea id="feedback-error" value={erro} onChange={e=>setErro(e.target.value)} maxLength={500}/></div></div></details>
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4"/>Até 3 envios a cada 15 minutos.</p><Button className="min-h-11 w-full sm:w-auto" disabled={!valid||submit.isPending} onClick={()=>submit.mutate()}>{submit.isPending?<RefreshCw className="mr-2 h-4 w-4 animate-spin"/>:<MessageSquarePlus className="mr-2 h-4 w-4"/>}{submit.isPending?'Enviando…':'Enviar feedback'}</Button></div>
 </CardContent></Card>}
 <section aria-labelledby="feedback-history-title" className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 id="feedback-history-title" className="text-lg font-semibold">{isPlatformAdmin?'Fila de feedbacks':'Meus protocolos'}</h2><p className="text-sm text-muted-foreground">{items.length} solicitações</p></div><Button variant="outline" className="min-h-11" onClick={()=>query.refetch()} disabled={query.isFetching}><RefreshCw className={`mr-2 h-4 w-4 ${query.isFetching?'animate-spin':''}`}/>Atualizar</Button></div>
 {query.isError?<ErrorState compact error={query.error} onRetry={()=>query.refetch()}/>:query.isLoading?<Card><CardContent className="py-10 text-center text-sm text-muted-foreground" role="status">Carregando protocolos…</CardContent></Card>:!items.length?<Card><CardContent className="flex flex-col items-center gap-2 py-10 text-center"><Lightbulb className="h-8 w-8 text-muted-foreground"/><p className="font-medium">Nenhum feedback por aqui</p></CardContent></Card>:items.map(item=><Card key={item.id}><CardContent className="space-y-3 pt-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm font-semibold">{item.protocolo}</p><p className="text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString('pt-BR')} · {categories[item.categoria]}</p></div>{isPlatformAdmin?<Select value={item.status} onValueChange={status=>update.mutate({id:item.id,status})}><SelectTrigger aria-label={`Status do protocolo ${item.protocolo}`} className="min-h-11 w-40"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(statuses).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>:<Badge variant={item.status==='resolvido'?'outline':'secondary'} className="gap-1">{item.status==='resolvido'?<CheckCircle2 className="h-3 w-3"/>:<Clock3 className="h-3 w-3"/>}{statuses[item.status]}</Badge>}</div><p className="whitespace-pre-wrap break-words text-sm">{item.mensagem}</p>{Object.keys(item.contexto||{}).length>0&&<div className="rounded-md bg-muted/50 p-3 text-xs text-muted-foreground"><p className="mb-1 font-medium text-foreground">Contexto informado</p>{Object.entries(item.contexto).map(([k,v])=><p key={k}>{k}: {v}</p>)}</div>}{isPlatformAdmin?<AdminReply item={item} onSaved={()=>query.refetch()}/>:item.resposta_publica&&<div className="rounded-md border-l-4 border-primary bg-primary/5 p-3"><p className="text-xs font-semibold">Resposta do EloLab</p><p className="mt-1 whitespace-pre-wrap text-sm">{item.resposta_publica}</p></div>}</CardContent></Card>)}</section></div>;
}
