import { useState } from 'react'; import { useQuery,useQueryClient } from '@tanstack/react-query'; import { supabase } from '@/integrations/supabase/client'; import { useSupabaseAuth } from '@/contexts/SupabaseAuthContext';
import { Card,CardContent,CardHeader,CardTitle,CardDescription } from '@/components/ui/card'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea'; import { Button } from '@/components/ui/button'; import { Switch } from '@/components/ui/switch'; import { Label } from '@/components/ui/label'; import { Bot,Save } from 'lucide-react'; import { toast } from 'sonner'; import { mensagemDeErro } from '@/lib/erros';
export default function PlatformIA(){const {user}=useSupabaseAuth();const qc=useQueryClient();const [form,setForm]=useState<any>(null);
 const config=useQuery({queryKey:['platform-ai-config'],queryFn:async()=>{const {data,error}=await (supabase as any).from('platform_ai_config').select('*').single();if(error)throw error;setForm(data);return data}});
 const usage=useQuery({queryKey:['platform-ai-usage'],queryFn:async()=>{const {data,error}=await (supabase as any).from('platform_ai_usage').select('*').gte('created_at',new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString());if(error)throw error;return data||[]}});
 const salvar=async()=>{try{const versao=(config.data?.versao||0)+1;const payload={...form,versao,updated_at:new Date().toISOString(),updated_by:user?.id};delete payload.id;const {error}=await (supabase as any).from('platform_ai_config').update(payload).eq('id',true);if(error)throw error;const {error:v}=await (supabase as any).from('platform_ai_prompt_versions').insert({versao,prompt:form.prompt_base,modelo:form.modelo_principal,criado_por:user?.id});if(v)throw v;qc.invalidateQueries({queryKey:['platform-ai-config']});toast.success('Configuração publicada.')}catch(e){toast.error('Falha ao publicar.',{description:mensagemDeErro(e)})}};
 const total=usage.data?.length||0,tokens=usage.data?.reduce((s:number,u:any)=>s+u.input_tokens+u.output_tokens,0)||0,custo=usage.data?.reduce((s:number,u:any)=>s+Number(u.custo_estimado),0)||0;
 if(!form)return <p>Carregando configuração...</p>;return <div className="space-y-6"><div><h1 className="text-2xl font-bold flex items-center gap-2"><Bot className="h-6 w-6"/>Governança da IA</h1><p className="text-muted-foreground">Modelos, limites, prompts versionados e consumo global.</p></div><div className="grid grid-cols-3 gap-3">{[['Requisições',total],['Tokens',tokens],['Custo estimado',`US$ ${custo.toFixed(4)}`]].map(([l,v])=><Card key={l}><CardContent className="pt-4"><p className="text-xs text-muted-foreground">{l}</p><p className="text-2xl font-bold">{v}</p></CardContent></Card>)}</div>
 <Card><CardHeader><CardTitle>Configuração ativa · versão {form.versao}</CardTitle><CardDescription>Alterações geram uma nova versão imutável do prompt.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-2"><Switch checked={form.ativo} onCheckedChange={v=>setForm({...form,ativo:v})}/><Label>IA habilitada</Label></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Modelo principal</Label><Input value={form.modelo_principal} onChange={e=>setForm({...form,modelo_principal:e.target.value})}/></div><div><Label>Fallback</Label><Input value={form.modelo_fallback||''} onChange={e=>setForm({...form,modelo_fallback:e.target.value||null})}/></div><div><Label>Temperatura</Label><Input type="number" min="0" max="2" step="0.1" value={form.temperatura} onChange={e=>setForm({...form,temperatura:Number(e.target.value)})}/></div><div><Label>Máximo de tokens</Label><Input type="number" min="100" max="16000" value={form.max_tokens} onChange={e=>setForm({...form,max_tokens:Number(e.target.value)})}/></div><div><Label>Limite mensal por clínica</Label><Input type="number" min="1" value={form.limite_mensal_clinica} onChange={e=>setForm({...form,limite_mensal_clinica:Number(e.target.value)})}/></div></div><div><Label>Prompt base de segurança</Label><Textarea rows={8} value={form.prompt_base} onChange={e=>setForm({...form,prompt_base:e.target.value})}/></div><Button onClick={salvar}><Save className="mr-2 h-4 w-4"/>Publicar nova versão</Button></CardContent></Card></div>}

