create table public.platform_operational_state(id boolean primary key default true check(id),bloqueio_emergencial boolean not null default false,somente_leitura boolean not null default false,mensagem text,updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));insert into public.platform_operational_state(id)values(true);
create table public.platform_feature_flags(id uuid primary key default gen_random_uuid(),chave text not null unique check(chave~'^[a-z0-9_]+$'),nome text not null,descricao text,ativo boolean not null default false,percentual smallint not null default 100 check(percentual between 0 and 100),destino text not null default 'todos' check(destino in('todos','clinica','plano')),destino_id text,updated_at timestamptz not null default now(),updated_by uuid references auth.users(id),check(destino='todos'or destino_id is not null));
alter table public.platform_operational_state enable row level security;alter table public.platform_feature_flags enable row level security;
create policy "plataforma controla operacao" on public.platform_operational_state for all to authenticated using(is_platform_admin()) with check(is_platform_admin() and updated_by=auth.uid());create policy "autenticado le operacao" on public.platform_operational_state for select to authenticated using(true);
create policy "plataforma gerencia flags" on public.platform_feature_flags for all to authenticated using(is_platform_admin()) with check(is_platform_admin() and updated_by=auth.uid());create policy "autenticado le flags" on public.platform_feature_flags for select to authenticated using(true);
create or replace function public.estado_operacional() returns jsonb language sql security definer set search_path=public stable as $$select jsonb_build_object('bloqueio_emergencial',bloqueio_emergencial,'somente_leitura',somente_leitura,'mensagem',mensagem)from platform_operational_state where id=true$$;grant execute on function public.estado_operacional() to authenticated;
create or replace function public.bloquear_escrita_operacional() returns trigger language plpgsql security definer set search_path=public as $$declare s platform_operational_state%rowtype;begin select * into s from platform_operational_state where id=true;if s.bloqueio_emergencial then raise exception 'Plataforma temporariamente indisponível: %',coalesce(s.mensagem,'bloqueio emergencial') using errcode='55000';end if;if s.somente_leitura then raise exception 'Plataforma em modo somente leitura: %',coalesce(s.mensagem,'alterações suspensas') using errcode='55000';end if;return coalesce(new,old);end$$;
do $$declare t text;begin foreach t in array array['pacientes','agendamentos','prontuarios','prescricoes','atestados','exames','coletas_laboratorio','resultados_laboratorio','lancamentos','pagamentos','contas_pagar','estoque','funcionarios','medicos','convenios','triagens'] loop if to_regclass('public.'||t)is not null then execute format('drop trigger if exists trg_controle_operacional on public.%I',t);execute format('create trigger trg_controle_operacional before insert or update or delete on public.%I for each row execute function public.bloquear_escrita_operacional()',t);end if;end loop;end$$;

