// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Em produção, as duas variáveis são obrigatórias. O fallback só existe no
// ambiente de testes, para que os testes unitários não dependam de um backend.
// Nunca deixar o frontend cair silenciosamente no Supabase Cloud: isso pode
// mascarar uma configuração incompleta do Coolify.
const isTest = import.meta.env.MODE === "test";
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (isTest ? "https://gebygucrpipaufrlyqqj.supabase.co" : "");
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  (isTest ? "test-publishable-key" : "");

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error("VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY são obrigatórias para executar o EloLab.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
